### ISSUE TITLE
Slow Response in Sensitive Message - Fikes 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#111]
Version 3.0.1

System hang after clicking the sensitive message tab - Fikes

**Comment by peterchanws** [comment]
Took >12 hrs. Results appear next day.

**Comment by peterchanws** [comment]
It seems to me the slowness is not related to the fix you made on version 3.03. I used v 2.1 to run Fikes and got the same slow processing on reg. expression search.

**Comment by peterchanws** [comment]
Version 3.0.2 RC2
No result after 3 hrs.

**Comment by peterchanws** [comment]
It took 10 minutes to show 428 messages matching the reg exp search in the full Bush archive.

**Comment by peterchanws** [comment]
Tt took less than 20 min to load 569 messages matching the the reg exp search in the full Terry archive (657000 messages)

**Comment by peterchanws** [comment]
It took less than 30 sec to load 17 messages matching the the reg exp search in the full Harrison archive (79000 messages)

**Comment by peterchanws** [comment]
Priority changed to low because these happened with Fikes archives only.

**Comment by hangal** [comment]
ePADD's slowness in bringing up the sensitive messages in the RF archive is related to bad/nonsensical data, and that's why it happens only on this archive (but could also happen on others, depending on the input data). 

Somewhere in the archive, there is a message (at least one, perhaps more) with text that looks like something below (I have pasted the beginning, but this goes on for more than 3M characters). It is probably a wayward attachment or something, but its recognized in the body of a message, not as an attachment, and it probably hits some sensitive message pattern somewhere. 

In trying to display the message honestly, like any other, we try to annotate this huge text. Which, besides being meaningless, takes a lot of time as you can imagine. We simply should avoid trying to annotate a message like this. 

So the question is: what policy should ePADD adopt for such messages?
e.g. 
- it won't annotate messages having more than M bytes
- it won't annotate messages having k strings of more than n characters unbroken by space?
- it will flag messages with length > 100,000 characters as likely errors in data quality report.
...

begin 600 ksl-hpkb-y2-final.tar.gz
M'XL("(/[O3<  VMS;"UH<&MB+7DR+69I;F%L+G1A<@#LG0N4&]5YQS>!I&')
M*6E($UXIJEQJ;#SVO$>"W1OV::^QO68?N(84&$FSVO&.9M8SHV77:=.D!2<N
MC_ J)K0AS0%,@#2E(24%4FB!TI2$-+Q*XI.$1R@A$#@-<" !6GI'VK5WM9)6
MVCLS^NX,.@<OVAU)\__-?#_=&7US->$8C+MSC.%91BWFF72:&=--U5C7YN.-
M9456423\DV-YD<,_699GA=+/V5L;*RN2(BBB(O'><A(GBFV2GRM1ZU9T7-7&
M+WF>;N0TN_9RV8)3]WE*H<2Y4*+/:QG8;:+&]M>F)PW55%W=,AE3G<JH]MJ\
M/K:\U\";G95EL=;VYP1);O,6D"7\:\[;_CPGLG@Y?Z-6O\5\^Z\?Z$\IZ@_?
M\SMME[6UO?/..T-#0^4_K/'^\7[?]MYWKOS"3=]]Z8CK_N:;^R^\[:???NN(
MW<E#KGQNS[Z;5WWMY<-O^]6F)UZ_^)["]]^X^ZZW#LO_Z],WC[_V^U><<,CP
MZ^<SUSUV<V''0\_<NO\XY3<O[;OW$_DKW^Z]T/KLO^Q_;/?=3[\\\^WTMJG'
M)^Y6IME#Q\<N./2K/RL^\[FA)Z9^:^NW'KGZR.W??/[1YS_P!K]G^$<?^:JC
M?_$#&Z<OT&;:>__QBK;G5C]QY(7;/F]_YT[ML</21PZL^M2/[GOKQ:'OO?_?
ME-7G'W[KKQ_?](?']3R8F]KPJ9=^W'W67=>_=-RG.[]C;WQAXU%'/7CQV6;[
M"W=W?K[W@U\\^J:9&[=_XYXGSSKIY9^<TO,_]W_EI*'!)Z_[DS>>%Y_=N^GT
M.]Q?=1>.O/KEIWK3[_QP[:[7QKGKO_;G+_+M;U_]#\><>NG''G]H^+&+C[WV
MCSYRW\Y#5SYZ;N\UJ[\_<]N,<]%#9D_^F-&=1QQ__]E?NN;_'.>7CYY^[8>=
M1XRIY"_VW?C)N[HO.$HZNN^6DPYY+W/,P\:6/?OV_^_WY%=^>>=-;3==?L.N
M"PL/7S.M_M=/;KGD[S8>/?7?]QZW]UO,]BM7'/)BWUW3H]O^_MR])Q?>/.V%
M6XR/'_%UYI]&5VDW?I++;S[IUS\_U7IJ9/T9 Y,W[OA!_K!3+IDYR_R/^XL?
MOVO?0T-C3^ZX_[!'&?2^VW?>=^IE_[G[HMN-?W[XJEM>??-SG6.O/??CGUW[
MI4_?L>L7-SPK_?SBMZ]:^^J]QQU[X^[OGK+_S7N^\= K8Y<<O^O6O4?M>?#?
M'SWVD=-V7_KJ\9^Y73__S#][_^7B%;DS][SQ(?V#VN[]?_S<\[=?WG?5;U9\
M!7WH@:<'IPK2RD=V]#S>^\Q9'[M*.K?C#W[[HT\9A]IG/+R:_?#[]NX^_J]&
M[SLWL^F*]>U?Z-UY4>=/]W#/'MF'DILO[7SIZ=S:T0VW]QE6V]$W?'3@]R[3
M?O<LM*IO[_HS5SSWI_ES5VG':U^_Z?"_GOG;F1.N-.]=M?$DZ\X]*Z69!^Y8
M>?7V'QSVP)<_<\VJ_)=WOS(]?LP>))]P[5^\+G9??_F6C?H-5YW]E_J^:\R3
M]?>TG=+*2H-YJ^5_W<QITVO'W8)!_AI+^-][M_?>_WE)E@6!E;WE%([GW_5_
M"+>.D8&137VH:V1K8M*VK#$G,6;9B6%7F](2VTI(.M:5%VEO[]C UU\0_[V]
M?77OP%!?S\C@T/:$J1N)$Y.KUZY.KFIO==!W;U5OM>I_Y/1^GE-4QBEFF-+V
M9KAEVZ!N_?,2+RMSXW^)E26A-/[CA'?K/XS;;/T/SVWFN6KOR%BYF40FG[4,
MR^Y<T5^Z)5QMVNU<48Z8,'1SHGP'_V5JP3VU?*^_W[N/2N*8]PKX7L=(5_>F
MOD3&LC'T3@[?'\+_]2:F\"/S9J=K3:)$1U=B2]?FOLZM0X.#_2QB.]9UX5^N
M&^FM7+)CZQ!>X6ZTU7OZDI94TSE/LT_N6->-$BM/Q$^T8:BOOS,YNU.7=N05
M2A)M4!UFLU;(:+93?O*J"_))-*Q/,UN-HL.,G&>5EAR>L RM<,XGG-)/QC$L

**Comment by hangal** [comment]
Currently, have added a rule that messages with body content > 100,000 characters will not be annotated.

**Comment by peterchanws** [comment]
version 3.1 
fixed.
