### ISSUE TITLE
Error when connecting to gmail a/c

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#116]
Version 3.01

Error # 2: No automatic configuration available for gmail.com, please use the option to provide a private (IMAP) server.

**Comment by hangal** [comment]
The gmail problem is due to a security/certificate issue at the Mozilla end.

In theory, it should have been fixed in the latest java release, but even that is not working.

I've asked Mozilla if they are going to fix it. Let's see if they do. If not, we'll have to implement some workaround. In the mean time, we can type imap.googlemail.com in the private IMAP server option and use the same credentials. (effectively, this is all the public IMAP server option does -- it auto-discovers the imap server address and the rest of the process is the same.)

I have also introduced more/better messages to the user when this error occurs.

**Comment by hangal** [comment]
A possible workaround is to include a secondary keystore in epadd, extract it from the war, and set up the HTTPS connection with this certificate (annoying, but possible.)
http://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore
http://stackoverflow.com/questions/18889058/programmatically-import-ca-trust-cert-into-existing-keystore-file-without-using
http://stackoverflow.com/questions/859111/how-can-i-use-different-certificates-on-specific-connections
This will turn security off altogether:
http://javaskeleton.blogspot.in/2010/07/avoiding-peer-not-authenticated-with.html
http://stackoverflow.com/questions/12060250/ignore-ssl-certificate-errors-with-java/42823950#42823950

Analyzing SSL errors:
https://dzone.com/articles/how-analyze-java-ssl-errors

Let's encrypt certs:
http://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates

**Comment by hangal** [comment]
Actually, rather a CERT issue, this seems to be a problem with the SSL handshake.
Chrome offers
Protocol TLS 1.2
Key Exchange ECDHE_RSA
Key Exchange Group P-256
Cipher AES_256_GCM

but looks Java doesn't do AES_256_GCM:
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]

As a result, Java is not even receiving a ServerHello. The solution is to upgrade the ciphers in the Java installation, but it seems this is not done unless one installs the Unlimited strength encryption from http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html. After installing these .jar files into <jre>/lib/security, the access to the ISPDB works.

**Comment by hangal** [comment]
If you install unlimited strength encryption, it works because the ciphers are:
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
and ServerHello picks TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by peterchanws** [comment]
I am fine telling people to type imap.googlemail.com in the imap server box. 
Priority lowered to low.

**Comment by peterchanws** [comment]
Version 3.0.2
problem still exists

**Comment by hangal** [comment]
Yes, this still exists because it is related to the Thunderbird end, not
ours.
You need to install Java unlimited strength encryption from
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html.
Then it will work. (The package is not available for 6-7 countries with
export control restrictions.)
However, it is cumbersome to make all users install extra software.

**Comment by peterchanws** [comment]
I suggest we make a remark in our "final" release telling people to put imap.googlemail.com in the imap server box.
