### ISSUE TITLE
Mismatch between Message Count in Browse Page and Message Page

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#143]
version 4.1
Bush small Windows Chrome

Browse page show
John Thrasher | 1 | 13
Steven West | 1 | 8

Message page for John Thrasher show 14 messages
Message page for Steven West show 11 messages

**Comment by hangal** [comment]
(Peter, pls provide exact URLs to help in reproducing).

I don't see the 2nd name in Bush-small at all.
The first name is present in correspondents, but not in person entities.

Anyway, assuming you are looking at the person entities page, remember we had discussed that the actual # of messages may be higher that the count in the entities pages because in some cases the term is not recognized as an entity in a message although it may hit in a full-text search.

**Comment by peterchanws** [comment]
Yes, I remember now.
