### ISSUE TITLE
Error when import 70 GB 4000 mbox files

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#149]
Version 4.1

 70 GB in ~4,000 mbox files.

"I went ahead and downloaded the 4.1 that was put out to see if there was any difference and there doesn’t appear to be.   On one,  I’ve loaded 22 fine and then I get the null error on 21.   On the other I’ve been able to load 21 and 22 and then I get the error on the 23rd"

**Comment by peterchanws** [comment]
Any updates?

**Comment by hangal** [comment]
How many messages does it have? Is it a personal archive or not? 
Can we get access to it?

We need to tell people how to report errors accurately. e.g. 

- Please mention the name of the screens you went through and input boxes filled.
- Precisely state the steps to reproduce the problem

This should be in the software as well on the error page.

**Comment by peterchanws** [comment]
She mentioned "probably about 500,000"




Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by peterchanws** [comment]
Reported to user that fixes will be ready by next release (version 5).

**Comment by hangal** [comment]
The file pst23 (pst23-20170901T060756Z-001.zip) seems to be the problematic one.

**Comment by hangal** [comment]
Still see this:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:740)
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:477)
at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:402)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:209)
at java.util.Arrays.sort(Arrays.java:1312)
at java.util.Arrays.sort(Arrays.java:1506)
at java.util.ArrayList.sort(ArrayList.java:1454)
at java.util.Collections.sort(Collections.java:141)
at edu.stanford.muse.util.EmailUtils.removeDupsAndSort(EmailUtils.java:692)
at edu.stanford.muse.email.MuseEmailFetcher.fetchAndIndexEmails(MuseEmailFetcher.java:556)
at edu.stanford.muse.webapp.JSPHelper.fetchAndIndexEmails(JSPHelper.java:354)
at org.apache.jsp.ajax.doFetchAndIndex_jsp._jspService(doFetchAndIndex_jsp.java:183)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

**Comment by peterchanws** [comment]
Peter will send the file via email.

**Comment by chinuhub** [comment]
There is an issue with DateDocument compareTo method. Starting from JDK 7 if compareTo breaks the contract (of compatibility with equals and irreflexivity) then this exception is thrown. For now one can resort to JDK 6 behaviour by specifying the jvm option during runtime by
-Djava.util.Arrays.useLegacyMergeSort=true

But going forward we should fix this issue.

**Comment by peterchanws** [comment]
temp fix with hack works fine

**Comment by peterchanws** [comment]
Do we need a permanent fix?

**Comment by peterchanws** [comment]
Any updates?

**Comment by hangal** [comment]
Under pst23/COUNCIL EMAIL/Licata GroupWise Archive (March 30, 2010)/2017 NL Responses - Sent Items.mbox

There are some duplicated messages, e.g. search for messages with the subject:
Council Business Meetings

There are at least 4 of these, with the same headers and content and dated:
Date: Wed, 07 Jan 1998 15:22:31 -0800
except that they have different Message-id's.
Message-Id: <62DDA85FE661044FBE12A309249707F75C3ECD018E@COSMCMS1.ad.seattle.gov>
and
Message-Id: <62DDA85FE661044FBE12A309249707F75C3ECDF283@COSMCMS1.ad.seattle.gov>
and
Message-Id: <62DDA85FE661044FBE12A309249707F75C3ECDF3A4@COSMCMS1.ad.seattle.gov>
and
Message-Id: <62DDA85FE661044FBE12A309249707F75C3ECDF4D2@COSMCMS1.ad.seattle.gov>

@peterchanws should these be considered different messages or not?

We currently consider these messages as different because the message-id header is included in the comparison. Should we remove it, i.e. if 2 messages have exactly same to/from/cc/bcc/date, is it enough to treat them as exactly the same (even if the message-id header is different).
Note that we don't show the message ID of a message in the browse screen. So the user may wonder why we're showing what seem to be duplicate messages.

**Comment by peterchanws** [comment]
what are the possible causes for different message ids with same message?

**Comment by hangal** [comment]
No idea -- depends on the email client.
