### ISSUE TITLE
Cleared for release label

### ISSUE THREAD

**Issue by hangal** [ePADD/epadd#166]
We need to add "Cleared for release" as a system general label. This is a special label. It will NOT be allowed to be set AT ALL (not just a warning) for messages where an actionable restriction has not expired. We're trusting system date and the date of the message for this purpose. For messages with an invalid date, all restriction labels are treated as non-actionable labels.

From processing export, only messages with this label will be written out. This label is not exported even though it is a general label. Adv. search or facets will have a way to filter out messages which already have "cleared for release" so that archivist can focus on only the newly unrestricted messages.

@chinuhub pls discuss with @peterchanws and @joshschneider

**Comment by chinuhub** [comment]
(For earlier discussion on this issue please refer to the comments of issue #165 )
The invariant for this label is;

This label can not be applied to a message that contains at least one not-expired restriction label. 

Two places where this invariant can be broken and hence require us to be careful are;

1. browse message window, a message having cleared for release label and then a user tries to add a time restriction label that has not expired for this message.
Expected behavioiur- user gets a message " this label can not be applied. To apply this message please remove 'cleared for release' label from this message."

2. browse message window, a message having a time restricted label that has not expired and then a user tries to add 'clared for release' label.
Expected behaviour- user get a message "this label can not be applied because the time restriction has not expired for this message. If you want to release this message to the next module please remove the time restriction label"

3. bulk-label page- user clicks set all on 'cleared for release' label for all messages in that docset 
Expected behaviour- user is informed in the confirmation box that this label will be applied to all messages except those which contain at least one non-expired time restriction labels.[no message passed from the backend after making changes]

4. bulk-label page- user clicks set all on a time restriction label;
Expected behaviour- user is informed in the confirmation box that "This action will also remove 'cleared for release' label in all those messages where this time restriction is not expired".[no message passed from the backend after making changes]

During export, following messages will be exported to the next module;
1. a message that does not contain any restriction label, or
2. a message that contains 'cleared for release label' and all timed restrictions (if any) have expired
[the conjunction check in 2 above is just a safety measure. Points 1,2,3,4 above will not allow this case to appear. However, this prevents any manual modification in the label assignment file]

@peterchanws @hangal  Please confirm this spec.

**Comment by peterchanws** [comment]
This spec. works fine for me.

**Comment by peterchanws** [comment]
Need to add advanced search functions to list all candidates for release - messages where ALL restriction period have expired and "Cleared for release" has not been applied.

**Comment by peterchanws** [comment]
When I execute the search "Expired restrictions (except 'Clear for release')", I also got messages with "Clear for release"

**Comment by hangal** [comment]
also @chinuhub can we do without the ALL_EXPIRED label?
This seems to convert a computable, transient var into a state, no?

**Comment by hangal** [comment]
also, is it "clear for release" or "cleared for release"?
@joshschneider any comment?

**Comment by joshschneider** [comment]
"Cleared for release" seems less prone to possible confusion. "Clear for release" might make it sound like an additional step is needed to actually do the clearing.

**Comment by peterchanws** [comment]
Could you change the label "Clear for Release" to Cleared for Release"?

**Comment by peterchanws** [comment]
Done.
