### ISSUE TITLE
Installing EPADD on an Ubuntu server

### ISSUE THREAD

**Issue by EgbertBleyenburg** [ePADD/epadd#238]
I understood that I can install epadd on an ubuntu server so we can access it from anywhere. 
So I simply try to run the epadd-standalone.jar there, but run into lots of problems. 

https://docs.google.com/document/d/1joUmI8yZEOnFzuWaVN1A5gAEA8UawC-UnKycdcuG5Xc/edit does not provide a how to for this setting.

Could anyone provide with info or a link to info on how to do this,  installing epadd on a remote server  or am I missing a fundamental point here?

Egbert

**Comment by peterchanws** [comment]
ePADD (appraisal, processing and delivery) is NOT designed to run on remote server. Only discover module is design to run in web server for read only access to a discover archive.


Peter Chan 

Digital Archivist

ePADD project Manager 

Stanford University Libraries 

Green Library, 557 Escondido Mall 

Stanford, CA  94305-6064 

(650) 924-2404 | pchan3@stanford.edu


________________________________

**Comment by EgbertBleyenburg** [comment]
Thanx a lot for your answer.



⁣Verzonden door Blue ​

Op 16 jul. 2018 15:17, om 15:17, Peter Chan <notifications@github.com> schreef:

**Comment by kylemcdonald** [comment]
Even though this isn't the desired behavior, it is possible. I was trying to get ePADD to act more like Datashare, and I was able to get it working by setting up a VNC server. Here are the steps I used https://gist.github.com/kylemcdonald/8b454d6c080732beca3ae01878056504

Because the software wasn't designed for this, I imagine this might open up a variety of security vulnerabilities for the machine it is installed on. At a bare minimum it's a good idea to password protect the server.
