### ISSUE TITLE
Expand existing sensitive messages tab

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#26]
Add description of regular expression in the presetqueries file.
System to pickup the descriptions of regular expressions in the file and show them as the description of the links to those messages.
Add disease/health entities 
Add link to sensitive lexicon
Add browse to cvs file for global actions
Add view email addresses tab to go to all email address and associated no of messages for actions. Cannot click to see messages.?? (not in wireframe yet)

![epadd - sensitive messages jan 2016 second draft](https://cloud.githubusercontent.com/assets/1050899/12409672/1efa057a-be21-11e5-9b93-1e98ed2ce6d8.png)

**Comment by hangal** [comment]
Hi Peter, Let us discuss this.

**Comment by glynnedw** [comment]
In the current beta (w/NER), it is very confusing. While I do believe the diseases and "sensitive" lexicon terms belong in a sensitive summary for review, I am thinking we do want to keep PII info separate. That is the first thing that gets reviewed and it's good to keep the set small. However, we need a new term rather than "sensitive" since it's actually PII/restricted data.

**Comment by glynnedw** [comment]
Comment re current beta: the sensitive browse button brings up the sensitive lexicon terms as facets and the hits have both (or either?) as results. I found it a little confusing especially as regular expression searches

**Comment by glynnedw** [comment]
didn't have a facet

**Comment by peterchanws** [comment]
ProdPad Idea #44
