### ISSUE TITLE
some lexicons not appear in default set

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#337]
v7 Dec 1

 	sensitive.cca.french.lex.txt 	and sensitive.cca.german.lex.txt 	
in https://github.com/ePADD/epadd/tree/master/WebContent/WEB-INF/classes/lexicon not copied in the default set

**Comment by hangal** [comment]
I think we're only doing english?

**Comment by peterchanws** [comment]
Some users sent Josh these foreign language lexicons to share with others. I see no reason to limit lexicon to English.

**Comment by chinuhub** [comment]
I have fixed the issue where the newly added lexicons files in WEB-INF/classes/lexicon were not being read by ePADD. 

However, as of now, we don't support two lexicon files with the same name which only differ in their language extension name, like sensitive.caa.french.lex.txt and sensitive.caa.german.lex.txt. We must rename one of them to something like sensitive.caa.french.txt and sensitive.caaa.french.txt.

Going forward, lexicons for multiple languages but similar category should be combined together. This is because the language layer is nowhere being used in ePADD for now. In this case,  the contents of senstive.caa.french.lex.txt and sensitive.caa.german.lex.txt can be put together in sensitive.english.lex.txt or in a separate file called sensitive.otherlanguages.lex.txt.

**Comment by peterchanws** [comment]
I have no problem changing filename. However,
sensitive.caa.german.lex.txt 
sensitive.caa.french.txt
sensitive.english.lex.txt
look different to me.

**Comment by peterchanws** [comment]
What about 
sensitive.caa.german.lex.txt to sensitive-ccc-german.lex.txt
sensitive.caa.french.txt to sensitive-caa-french.txt

**Comment by chinuhub** [comment]
there should be a language name in the suffix. I suggest sensitive-ccc-german.german.lex.txt and sensitive-caa-french.french.lext.text

**Comment by peterchanws** [comment]
Fine with me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peterchanws** [comment]
fixed
