### ISSUE TITLE
Message count from "Correspondent" screen is very different from clicking the correspondent

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#35]
<img width="885" alt="screen shot 2016-01-20 at 12 10 32 pm" src="https://cloud.githubusercontent.com/assets/1050899/12461710/39719004-bf6f-11e5-94fd-d2f962f88613.png">
<img width="965" alt="screen shot 2016-01-20 at 12 10 56 pm" src="https://cloud.githubusercontent.com/assets/1050899/12461712/3b9a8bc4-bf6f-11e5-8731-46dda89a8d7a.png">

Elise Bernhardt

**Comment by vihari** [comment]
@peterchanws Cannot reproduce this problem. 
It looks like the problem is specific to the contact and archive.
Can you provide more information on what archive this is observed on, URLs of the snapshot pages, the addresses included in the contact "Elise Bernhardt" (the ones you see when you hover over the contact). Please send these over email if you do not want to put them here. 
None of the counts on the correspondents listing page reflects the actual count you get when you search. One sanity check is that the number of documents in browse page < (number of mentions + number of outgoing messages + number of incoming messages). The sum is little (generally) higher than the actual number because a correspondent can be both in FROM and TO lists. Clearly the snapshot you provided failed this sanity check. Please send me the details I requested and I will look into it.

**Comment by peterchanws** [comment]
I got the reported incident from Creeley.
The same happens to Bush (small).
![capture1](https://cloud.githubusercontent.com/assets/1050899/12837737/43e037a4-cb7a-11e5-9238-8d2b0801fe49.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1050899/12837739/4713a712-cb7a-11e5-8366-a8fcba99d6bc.PNG)
