### ISSUE TITLE
Upload label cause error if there are messages with labels 

### ISSUE THREAD

**Issue by peterchanws** [ePADD/epadd#359]
ver Jan 29-2
System should add prefix (new-) to label(s) with same name. Since an archive will most likely have messages assigned with labels on errors, the upload function will work most of the time.

![capture1](https://user-images.githubusercontent.com/1050899/51944457-f3aece00-23d0-11e9-89f9-ccc5597f9c4e.PNG)

**Comment by chinuhub** [comment]
The spec is as following;

1. If uploaded label list contains system labels then they won't be merged.
2. Any other label, present in the uploaded file, will be prefixed by "new".
Case: Let 'abc' and 'newabc' be two labels in the archive. User uploads a label list that contains a label named 'abc'. We can't just replace it with 'newabc' because the system already contains 'newabc'.

**Comment by hangal** [comment]
@chinuhub confirms this has been implemented in the code. He will test it and close this issue if it is fixed.
