### ISSUE TITLE
mbox exports are lossy and unsuitable for preservation

### ISSUE THREAD

**Issue by axfelix** [ePADD/epadd#372]
Hi,

I've been checking in with ePADD development lately and have been really impressed by how far along it's come to being suitable for production use for us, with the exception of the mbox exports, which have substantial issues. Ideally we'd like to use them for preservation purposes, disposing of the mbox files we're importing to ePADD before cleaning and redacting them, but right now there are three big problems with that:

1) Timestamps appear to be changed in the ePADD mbox output from the original -- this seems like it could be a timezone issue, as the minutes remain the same, but the hours appear to be arbitrarily different from imports.

2) There are string formatting issues: linebreaks and special characters don't always appear to be preserved properly. Not sure how your unicode pipeline works but it seems to be worse in the export than in the ePADD interface; can provide examples here.

3) There isn't a good way of preserving folder hierarchy in cases where an ingested mbox was originally sorted by folder; you have to manually make multiple exports from ePADD, which is laborious and error-prone.

Let me know if I should close this and track each of these separately. Thanks!

**Comment by WhenSkiesAbove** [comment]
Not sure if there's been any progress on this or if reiterating the above is considered badgering (apologies if it is - first time Github user here), but this is an issue for me as well. After exporting MBOX files from work done in the appraisal and processing module, I decided to re-import them into the appraisal module and there is no folder hierarchy, just one folder containing everything. I can't speak to the other issues listed above (just due to not knowing where to look), but this would be an issue for me as well, as the plan was to ingest the appraised and processed MBOX files into Archivematica for long-term preservation.

Thanks!

**Comment by hangal** [comment]
@ajlouie @jfarwer this is something that may be relevant for epadd+.

**Comment by jfarwer** [comment]
@hangal The exported Mbox file contains for each message a line X-ePADD-Folder followed by the folder name. However, when re-importing, the name and path of the Mbox file containing the exported messages is used, so indeed everything is in one folder. It shouldn’t be too difficult to make ePADD using the information in X-ePADD-Folder (if present) so the old folder structure is preserved. I will have a look into that.
