### ISSUE TITLE
Delivery module does not allow to navigate to other modules

### ISSUE THREAD

**Issue by bencomp** [ePADD/epadd#4]
Whereas the *settings* page in the other modules allow one to "change the module" (this feels very unintuitive, but that's a different issue), when I switch to the Delivery module, I cannot switch back because the settings page does not show this option anymore.

**Comment by peterchanws** [comment]
Thank for your comments. The delivery module is designed to be deployed in the reading rooms of respective institutions for researcher use. As a result, we intentionally disable the switching back to other modules once it is set to the Delivery module.

**Comment by bencomp** [comment]
Interesting. How do I get back when I accidentally switched modules? Restart the application? How do you then prevent reading room users from restarting and accessing the other modules?

**Comment by peterchanws** [comment]
Yes, you have to restart the application in order to switch from delivery mode to appraisal/processing mode. The purpose for this design is to avoid confusion to researchers in the reading room. Even when the researchers restart the program and use the appraisal/processing modules, the dataset before processing is not in the reading room computer.

**Comment by bencomp** [comment]
Thanks for the explanation. I guess this is not a real issue then.
