### ISSUE TITLE
Can't start ePADD without restarting computer

### ISSUE THREAD

**Issue by vmaches** [ePADD/epadd#99]
When I click on the ePADD icon on my desktop, nothing happens unless I'm starting from a restart. If my computer has just restarted, then ePADD will open. The same thing happened on a different computer.

**Comment by peterchanws** [comment]
Please use https://epadd.nimeyo.com/ to ask questions about ePADD.

**Comment by joshschneider** [comment]
You must fully quit ePADD in order to restart the application, by closing it from the icon in the task bar (Windows) or top menu bar (OSX).

Side note: These forums are intended for developer bug reports only. Please report any end user bugs to the ePADD forums: epadd.nimeyo.com<http://epadd.nimeyo.com>.

On Oct 20, 2016, at 2:39 PM, vmaches <notifications@github.com<mailto:notifications@github.com>> wrote:


When I click on the ePADD icon on my desktop, nothing happens unless I'm starting from a restart. If my computer has just restarted, then ePADD will open. The same thing happened on a different computer.

-
